import { TYPOGRAPHY, SPACING } from '../../constants';
import type { ThemeColors, ThemeShadows } from '../../theme';

const createImageModelsStylesPart1 = (colors: ThemeColors, _shadows: ThemeShadows) => ({
  recToggle: {
    padding: 12,
    borderRadius: 12,
    backgroundColor: colors.surface,
  },
  recToggleActive: {
    backgroundColor: `${colors.primary}15`,
  },
  recHint: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginBottom: 8,
    backgroundColor: `${colors.primary}10`,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: `${colors.primary}30`,
  },
  recHintText: {
    ...TYPOGRAPHY.meta,
    color: colors.textSecondary,
    flex: 1,
  },
  imageModelsSection: {
    paddingHorizontal: 16,
  },
  imageModelsList: {
    paddingHorizontal: 16,
    marginBottom: 24,
  },
  recommendedBadge: {
    backgroundColor: colors.primary,
    alignSelf: 'flex-start' as const,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    marginLeft: 12,
    marginBottom: -1,
  },
  recommendedBadgeText: {
    ...TYPOGRAPHY.meta,
    color: colors.background,
    fontWeight: '700' as const,
    fontSize: 10,
    letterSpacing: 0.5,
  },
  imageModelCard: { marginBottom: 12 },
  imageModelHeader: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'flex-start' as const,
    marginBottom: 12,
  },
  imageModelInfo: { flex: 1 },
  imageModelName: { ...TYPOGRAPHY.h2, color: colors.text, marginBottom: 4 },
  imageModelDesc: { ...TYPOGRAPHY.bodySmall, color: colors.textSecondary, marginBottom: 4 },
  imageModelSize: { ...TYPOGRAPHY.meta, color: colors.textMuted },
  activeBadge: {
    backgroundColor: `${colors.info}25`,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    marginLeft: 8,
  },
  activeBadgeText: { ...TYPOGRAPHY.meta, color: colors.info },
  imageModelActions: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 12,
  },
  setActiveButton: {
    backgroundColor: `${colors.primary}20`,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
  },
  setActiveButtonText: { ...TYPOGRAPHY.bodySmall, color: colors.primary },
  deleteImageButton: { padding: 8 },
  imageModelCompactRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    backgroundColor: colors.surface,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    marginBottom: 6,
    gap: 8,
  },
  imageModelCompactInfo: { flex: 1, gap: 2 },
  imageModelCompactName: { ...TYPOGRAPHY.bodySmall, color: colors.text, fontWeight: '600' as const },
  imageModelCompactMeta: { ...TYPOGRAPHY.metaSmall, color: colors.textMuted },
  activeBadgeCompact: {
    backgroundColor: `${colors.info}25`,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
  },
  activeBadgeCompactText: { ...TYPOGRAPHY.metaSmall, color: colors.info, fontWeight: '600' as const },
  setActiveButtonCompact: {
    backgroundColor: `${colors.primary}20`,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
  },
  setActiveButtonCompactText: { ...TYPOGRAPHY.metaSmall, color: colors.primary, fontWeight: '600' as const },
  deleteImageButtonCompact: { padding: 4 },
  availableTitle: { ...TYPOGRAPHY.bodySmall, color: colors.textMuted, marginBottom: 8 },
});

const createImageModelsStylesPart2 = (colors: ThemeColors, _shadows: ThemeShadows) => ({
  downloadImageButton: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    backgroundColor: 'transparent' as const,
    borderWidth: 1,
    borderColor: colors.primary,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    gap: 8,
  },
  downloadImageButtonText: { ...TYPOGRAPHY.body, color: colors.primary },
  imageDownloadProgress: { alignItems: 'center' as const, gap: 8 },
  imageDownloadText: { ...TYPOGRAPHY.bodySmall, color: colors.textSecondary },
  imageProgressBar: {
    width: '100%' as const,
    height: 6,
    backgroundColor: colors.surfaceLight,
    borderRadius: 3,
    overflow: 'hidden' as const,
  },
  imageProgressFill: {
    height: '100%' as const,
    backgroundColor: colors.primary,
    borderRadius: 3,
  },
  allDownloadedText: {
    ...TYPOGRAPHY.bodySmall,
    color: colors.textMuted,
    textAlign: 'center' as const,
    paddingVertical: 16,
  },
  hfLoadingContainer: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: 10,
    paddingVertical: 24,
  },
  hfErrorContainer: { alignItems: 'center' as const, paddingVertical: 20, gap: 12 },
  hfErrorText: { ...TYPOGRAPHY.bodySmall, color: colors.error, textAlign: 'center' as const },
  retryButton: {
    backgroundColor: `${colors.primary}20`,
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 8,
  },
  retryButtonText: { ...TYPOGRAPHY.bodySmall, color: colors.primary },
  textModelsSectionTitle: { ...TYPOGRAPHY.h2, color: colors.text, marginBottom: 12, marginTop: 8 },
  imageSearchRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 8,
    marginBottom: 12,
  },
  imageSearchInput: {
    ...TYPOGRAPHY.body,
    flex: 1,
    backgroundColor: colors.surface,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 10,
    color: colors.text,
    borderWidth: 1,
    borderColor: colors.border,
  },
  backendFilterRow: { flexDirection: 'row' as const, gap: 8, marginBottom: 12 },
  modelNameRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 8,
    marginBottom: 4,
  },
  badgeRow: { flexDirection: 'row' as const, gap: 6, marginBottom: 4 },
  backendBadge: { paddingHorizontal: 8, paddingVertical: 2, borderRadius: 6 },
  cpuBadge: { backgroundColor: `${colors.primary}25` },
  npuBadge: { backgroundColor: '#FF990025' },
  backendBadgeText: { ...TYPOGRAPHY.label, color: colors.text },
  variantBadge: {
    backgroundColor: colors.surfaceLight,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
  },
  variantBadgeText: { ...TYPOGRAPHY.label, color: colors.textSecondary },
  variantHint: { ...TYPOGRAPHY.label, color: colors.textMuted, marginBottom: 2 },
});

export const createImageModelsStyles = (colors: ThemeColors, shadows: ThemeShadows) => ({
  ...createImageModelsStylesPart1(colors, shadows),
  ...createImageModelsStylesPart2(colors, shadows),
});
