import { TYPOGRAPHY, SPACING } from '../../constants';
import type { ThemeColors, ThemeShadows } from '../../theme';
import { createImageModelsStyles } from './imageStyles';

const createBaseStyles = (colors: ThemeColors, shadows: ThemeShadows) => ({
  flex1: { flex: 1 },
  backButton: { padding: 4, marginRight: 8 },
  searchContainerNoPadding: { paddingHorizontal: 0 },
  container: { flex: 1, backgroundColor: colors.background },
  header: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    ...shadows.small,
    zIndex: 1,
  },
  title: { ...TYPOGRAPHY.h2, color: colors.text, flex: 1 },
  downloadManagerButton: { padding: 8, position: 'relative' as const },
  downloadBadge: {
    position: 'absolute' as const,
    top: 2,
    right: 2,
    backgroundColor: colors.primary,
    borderRadius: 10,
    minWidth: 18,
    height: 18,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    paddingHorizontal: 4,
  },
  downloadBadgeText: { ...TYPOGRAPHY.label, color: colors.text },
  tabBar: {
    flexDirection: 'row' as const,
    paddingHorizontal: 16,
    gap: 24,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    marginBottom: 12,
  },
  tabItem: { paddingVertical: 10, alignItems: 'center' as const },
  tabText: { ...TYPOGRAPHY.body, color: colors.textMuted },
  tabTextActive: { color: colors.text, fontWeight: '700' as const },
  tabIndicator: {
    height: 2,
    backgroundColor: colors.primary,
    borderRadius: 1,
    marginTop: 4,
    alignSelf: 'stretch' as const,
  },
  imageTabContent: { flex: 1 },
  searchContainer: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    paddingHorizontal: 16,
    paddingBottom: 16,
    gap: 8,
  },
  searchInput: {
    ...TYPOGRAPHY.body,
    flex: 1,
    backgroundColor: colors.surface,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    color: colors.text,
  },
  importButton: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: 10,
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 8,
    paddingVertical: 12,
    borderWidth: 2,
    borderStyle: 'dashed' as const,
    borderColor: `${colors.primary}60`,
    borderRadius: 12,
    backgroundColor: `${colors.primary}08`,
  },
  importButtonText: { ...TYPOGRAPHY.body, color: colors.primary },
  importProgressCard: {
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 8,
    padding: 16,
    backgroundColor: colors.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 10,
  },
  importProgressHeader: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 8,
  },
  importProgressText: { ...TYPOGRAPHY.bodySmall, color: colors.text, flex: 1 },
  importProgressPercent: { ...TYPOGRAPHY.meta, color: colors.textMuted, textAlign: 'center' as const },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    gap: 16,
  },
  loadingText: { ...TYPOGRAPHY.body, color: colors.textSecondary },
  listContent: { paddingHorizontal: 16, paddingBottom: 32 },
  deviceBanner: {
    backgroundColor: `${colors.primary}12`,
    borderRadius: 8,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    marginBottom: SPACING.lg,
    borderWidth: 1,
    borderColor: `${colors.primary}30`,
  },
  deviceBannerText: { ...TYPOGRAPHY.meta, color: colors.primary },
  deviceBannerWarning: { color: colors.error, marginTop: 2 },
  emptyCard: { alignItems: 'center' as const, padding: 32 },
  emptyText: { color: colors.textSecondary, textAlign: 'center' as const },
});

const createFilterStyles = (colors: ThemeColors, _shadows: ThemeShadows) => ({
  filterBar: { marginBottom: 4, paddingBottom: 4 },
  filterPillRow: {
    paddingHorizontal: 16,
    gap: 8,
    alignItems: 'center' as const,
  },
  filterPill: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderRadius: 20,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 4,
  },
  filterPillActive: { backgroundColor: `${colors.primary}25`, borderColor: colors.primary },
  filterPillText: { ...TYPOGRAPHY.bodySmall, color: colors.textSecondary },
  filterPillTextActive: { color: colors.primary },
  filterCountBadge: {
    backgroundColor: colors.primary,
    borderRadius: 10,
    minWidth: 18,
    height: 18,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    paddingHorizontal: 4,
  },
  filterCountText: { ...TYPOGRAPHY.labelSmall, color: colors.background, fontWeight: '700' as const },
  clearFiltersButton: { paddingHorizontal: SPACING.md, paddingVertical: SPACING.sm },
  clearFiltersText: { ...TYPOGRAPHY.bodySmall, color: colors.error },
  filterExpandedContent: { paddingHorizontal: 16, paddingTop: 8, paddingBottom: 4 },
  filterChipWrap: { flexDirection: 'row' as const, flexWrap: 'wrap' as const, gap: 8 },
  filterChip: {
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderRadius: 8,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  filterChipActive: { backgroundColor: `${colors.primary}25`, borderColor: colors.primary },
  filterChipText: { ...TYPOGRAPHY.bodySmall, color: colors.textSecondary },
  filterChipTextActive: { color: colors.primary },
  filterToggle: { padding: 12, borderRadius: 12, backgroundColor: colors.surface },
  filterToggleActive: { backgroundColor: `${colors.primary}15` },
  filterDot: {
    position: 'absolute' as const,
    top: 6,
    right: 6,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.primary,
  },
});

const createTextModelsStyles = (colors: ThemeColors, _shadows: ThemeShadows) => ({
  modelInfoCard: { marginHorizontal: 16, marginTop: 12, marginBottom: 16 },
  authorRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    marginBottom: 8,
    gap: 8,
  },
  modelAuthor: { ...TYPOGRAPHY.body, color: colors.textSecondary },
  credibilityBadge: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    gap: 4,
  },
  credibilityIcon: { ...TYPOGRAPHY.label },
  credibilityText: { ...TYPOGRAPHY.meta },
  modelDescription: { ...TYPOGRAPHY.body, color: colors.text, marginBottom: 12 },
  modelStats: { flexDirection: 'row' as const, gap: 16 },
  statText: { ...TYPOGRAPHY.meta, color: colors.textMuted },
  sectionTitle: { ...TYPOGRAPHY.h3, color: colors.text, paddingHorizontal: 16, marginBottom: 4 },
  sectionSubtitle: {
    ...TYPOGRAPHY.body,
    color: colors.textSecondary,
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  recommendedTitle: { ...TYPOGRAPHY.meta, color: colors.textMuted, marginBottom: SPACING.md },
});

export const createStyles = (colors: ThemeColors, shadows: ThemeShadows) => ({
  ...createBaseStyles(colors, shadows),
  ...createFilterStyles(colors, shadows),
  ...createTextModelsStyles(colors, shadows),
  ...createImageModelsStyles(colors, shadows),
});
