import type { ThemeColors, ThemeShadows } from '../../theme';
import { TYPOGRAPHY, SPACING } from '../../constants';

export const createStyles = (colors: ThemeColors, shadows: ThemeShadows) => ({
  flex1: { flex: 1 },
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.surface,
    ...shadows.small,
    zIndex: 1,
    gap: SPACING.md,
  },
  backButton: { padding: SPACING.xs },
  title: { ...TYPOGRAPHY.h2, flex: 1, color: colors.text },
  scrollView: { flex: 1 },
  content: {
    paddingHorizontal: SPACING.lg,
    paddingTop: SPACING.lg,
    paddingBottom: SPACING.xxl,
  },
  section: { marginBottom: SPACING.lg },
  sectionTitle: {
    ...TYPOGRAPHY.label,
    textTransform: 'uppercase' as const,
    color: colors.textMuted,
    marginBottom: SPACING.md,
    letterSpacing: 0.3,
  },
  settingHelp: {
    ...TYPOGRAPHY.bodySmall,
    color: colors.textMuted,
    marginBottom: SPACING.md,
    lineHeight: 18,
  },
  textArea: {
    ...TYPOGRAPHY.bodySmall,
    backgroundColor: colors.surfaceLight,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    padding: SPACING.md,
    color: colors.text,
    minHeight: 80,
    textAlignVertical: 'top' as const,
  },
  toggleRow: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    paddingVertical: SPACING.sm,
    marginBottom: SPACING.sm,
  },
  toggleInfo: { flex: 1, marginRight: SPACING.md },
  toggleLabel: { ...TYPOGRAPHY.body, color: colors.text },
  toggleDesc: {
    ...TYPOGRAPHY.bodySmall,
    color: colors.textMuted,
    marginTop: 2,
    lineHeight: 18,
  },
  toggleNote: {
    ...TYPOGRAPHY.bodySmall,
    color: colors.textMuted,
    lineHeight: 18,
    backgroundColor: colors.surfaceLight,
    padding: SPACING.md,
    borderRadius: 8,
  },
  sliderSection: {
    marginTop: SPACING.lg,
    paddingTop: SPACING.lg,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  sliderHeader: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    marginBottom: SPACING.xs,
  },
  sliderLabel: { ...TYPOGRAPHY.body, color: colors.text },
  sliderValue: { ...TYPOGRAPHY.body, fontWeight: '400' as const, color: colors.primary },
  sliderDesc: {
    ...TYPOGRAPHY.bodySmall,
    color: colors.textMuted,
    marginBottom: SPACING.sm,
    lineHeight: 18,
  },
  warningText: {
    ...TYPOGRAPHY.bodySmall,
    color: colors.warning,
    marginTop: SPACING.xs,
    lineHeight: 18,
  },
  slider: { width: '100%' as const, height: 40 },
  strategyButtons: {
    flexDirection: 'row' as const,
    gap: SPACING.sm,
    marginTop: SPACING.md,
  },
  settingSection: { marginTop: SPACING.lg },
  settingLabel: { ...TYPOGRAPHY.body, color: colors.text, marginBottom: SPACING.xs },
  settingDesc: {
    ...TYPOGRAPHY.bodySmall,
    color: colors.textMuted,
    marginBottom: SPACING.md,
    lineHeight: 18,
  },
  buttonRow: { flexDirection: 'row' as const, gap: SPACING.sm },
});
